import '../styles/globals.scss'
import type { AppProps } from 'next/app'
import Head from 'next/head'
import Layout from '../components/Layout/Layout'
import { Provider } from 'react-redux'
import { store } from '../store/store'

export default function App({ Component, pageProps }: AppProps) {
  return (
  <>
    <Head>
    <title>Create Next App</title>
    <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="/favicon.ico" />
    </Head>
   <Provider store={store}>
    <Layout>
      <Component {...pageProps} />
      </Layout>
   </Provider>
  </>
  )
  
}
